### ISSUE TITLE
Error during msticnb initialization

### ISSUE THREAD

**Issue by AlexSta2019** [microsoft/msticnb#21]
Environment details:
- Linux (ubuntu 20.04 - Standard D2s v3 (2 vcpus, 8 GiB memory))
- Python 3.8.10
- Installed all pre-reqs for running the Azure Automated Notebooks from https://github.com/Azure/Azure-Sentinel-Notebooks. I also added/installed msticpy[ml] & gir1.2-secret-1.

Steps to repro:
After I launch AutomatedNotebooks-Manager.ipynb using papermill, the AutomatedNotebooks-IncidentTriage.ipynb is triggered and at some point the msticnb should be initialized. The code looks like this:
```
# Set up notebooklets
nb.init(qry_prov)
timespan = TimeSpan(start=datetime.now() - timedelta(days=7))
```

This is where I can the following error:
```
~/.local/lib/python3.8/site-packages/msticpy/common/provider_settings.py in _get_settings(config_section, provider_name, conf_group, name_map)
    176     if not conf_group:
    177         return ProviderArgs()
--> 178     setting_dict: ProviderArgs = ProviderArgs(conf_group.copy())
    179 
    180     for arg_name, arg_value in conf_group.items():

AttributeError: 'str' object has no attribute 'copy'
```
NOTE: the error message is longer than this, please let me know if I should paste the entire message.

**Comment by ianhelle** [comment]
Hi @AlexSta2019,
Thanks for reporting this. I'm not 100% certain but it looks like this could be caused by a problem with your msticpconfig.yaml
The `conf_group` in the context of the code above is the `Args` section of a TI or Data provider entry. This should always be a dict and should look like the settings in the following. I.e. Args should have one or more keys (like AuthKey, AppID) and that, in turn can either be a string (for directly storing the value) or another dict for storing values in env vars or in Azure Key Vault.

```yaml
TIProviders:
  OTX:
    Args:
      AuthKey: sdfg7f89g7fs0d97gfdag
    Primary: True
    Provider: "OTX"
  VirusTotal:
    Args:
      AuthKey:
        EnvironmentVar: "VIRUSTOTAL_AUTH"
    Primary: True
    Provider: "VirusTotal"
  AnOtherProvider:
    Args:
      AuthKey:
        KeyVault: 
    Primary: True
    Provider: "VirusTotal"
  ...
```

Can you check your config to make sure it looks OK.
If this is the problem I will add an issue (in microsoft/msticpy repo) to add a check for this in the config validation, so that it's detectable earlier and with a bit more clarity.
